[build]
  command   = "npm run build"
  publish   = "dist/"

[functions]
  # apunta a las funciones generadas por Astro
  directory = "dist/functions"

[dev]
  functions = "dist/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "br"
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# ✅ Optimizar fuentes web
[[headers]]
  for = "/fonts/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff2"

# ✅ Preload imágenes críticas si se conocen (ejemplo: hero image)
[[headers]]
  for = "/imgs/calculator.webp"
  [headers.values]
    Link = "</imgs/calculator.webp>; rel=preload; as=image"

# ✅ CSS y JS deben tener caching fuerte
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"