[build]
  command   = "npm run build"
  publish   = "dist/"

[functions]
  # apunta a las funciones generadas por Astro
  directory = "dist/functions"

[dev]
  functions = "dist/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "br"
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
